services:
  - type: web
    name: gestion-maison
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: SUPABASE_URL
        sync: false
        # URL de votre projet Supabase (ex: https://xxxxx.supabase.co)
      - key: SUPABASE_ANON_KEY
        sync: false
        # Clé anonyme de votre projet Supabase
      - key: MONGODB_URI
        sync: false
        # URI MongoDB Atlas (fallback si Supabase indisponible)
    healthCheckPath: /
    autoDeploy: true
    branch: master